#!/bin/bash

# First attempt
#chmod 755 $PYFILE
#./$PYFILE

# Better way with some error handling

#check if environment variable is set
[ -z "&PYFILE" ] && { ECHO "Error: PYFILE environment variable is not set."; exit 1; } || python3 "&PYFILE"
